CREATE TABLE recurring_transactions (
    id VARCHAR(64) PRIMARY KEY,
    contract_id VARCHAR(64) NULL,
    account_id VARCHAR(64) NOT NULL,
    source_pocket_id VARCHAR(64) NULL,
    destination_pocket_id VARCHAR(64) NULL,
    partner_id VARCHAR(64) NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    amount BIGINT NOT NULL,
    currency_code VARCHAR(16) NOT NULL,
    transaction_type VARCHAR(32) NOT NULL,
    first_occurrence_date VARCHAR(32) NOT NULL,
    final_occurrence_date VARCHAR(32) NULL,
    recurrence_type VARCHAR(32) NOT NULL,
    skip_count INTEGER NOT NULL DEFAULT 0,
    days_of_week TEXT NULL,
    weeks_of_month TEXT NULL,
    days_of_month TEXT NULL,
    months_of_year TEXT NULL,
    last_materialized_date VARCHAR(32) NULL,
    previous_version_id VARCHAR(64) NULL,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at BIGINT NOT NULL,
    CONSTRAINT fk_recurring_transactions_contract FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE SET NULL,
    CONSTRAINT fk_recurring_transactions_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_recurring_transactions_source_pocket FOREIGN KEY (source_pocket_id) REFERENCES pockets(id) ON DELETE SET NULL,
    CONSTRAINT fk_recurring_transactions_destination_pocket FOREIGN KEY (destination_pocket_id) REFERENCES pockets(id) ON DELETE SET NULL,
    CONSTRAINT fk_recurring_transactions_partner FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE SET NULL,
    CONSTRAINT fk_recurring_transactions_currency FOREIGN KEY (currency_code) REFERENCES currencies(code),
    CONSTRAINT fk_recurring_transactions_previous_version FOREIGN KEY (previous_version_id) REFERENCES recurring_transactions(id) ON DELETE SET NULL
);
