spring:
  application:
    name: plannr-server
  docker:
    compose:
      file: ${PLANNR_DOCKER_COMPOSE_FILE:apps/server/compose.yml}
      lifecycle-management: ${PLANNR_DOCKER_COMPOSE_LIFECYCLE_MANAGEMENT:${plannr.database.docker-compose.lifecycle-management:start_and_stop}}
  r2dbc:
    url: r2dbc:postgresql://${plannr.database.host}:${plannr.database.port}/${plannr.database.name}
    username: ${plannr.database.username}
    password: ${plannr.database.password}
  flyway:
    url: jdbc:postgresql://${plannr.database.host}:${plannr.database.port}/${plannr.database.name}
    user: ${plannr.database.username}
    password: ${plannr.database.password}
  @springConfigImport@
server:
  port: 9000
plannr:
  database:
    host: ${PLANNR_DB_HOST:192.168.1.202}
    port: ${PLANNR_DB_PORT:5432}
    name: ${PLANNR_DB_NAME:plannr}
    username: ${PLANNR_DB_USERNAME:plannr}
    password: ${PLANNR_DB_PASSWORD:plannr}
    docker-compose:
      lifecycle-management: start_and_stop
  projections:
    dirty-scope-delay-ms: 30000
    full-rebuild-delay-ms: 3600000
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    db:
      enabled: false
