spring:
  application:
    name: plannr-server
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:h2:mem:///plannr;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${SPRING_DB_USERNAME:sa}
    password: ${SPRING_DB_PASSWORD:}
  flyway:
    url: ${SPRING_FLYWAY_URL:jdbc:h2:mem:plannr;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    user: ${SPRING_DB_USERNAME:sa}
    password: ${SPRING_DB_PASSWORD:}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    db:
      enabled: false
