CREATE TABLE transaction_materializations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    transaction_template_id BIGINT NOT NULL,
    transaction_date VARCHAR(32) NOT NULL,
    source_pocket_id BIGINT NULL,
    destination_pocket_id BIGINT NULL,
    partner_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    amount BIGINT NOT NULL,
    currency_code VARCHAR(16) NOT NULL,
    transaction_type VARCHAR(32) NOT NULL,
    created_at BIGINT NOT NULL,
    CONSTRAINT fk_transaction_materializations_template
        FOREIGN KEY (transaction_template_id) REFERENCES transaction_templates(id) ON DELETE CASCADE,
    CONSTRAINT fk_transaction_materializations_source_pocket
        FOREIGN KEY (source_pocket_id) REFERENCES pockets(id) ON DELETE SET NULL,
    CONSTRAINT fk_transaction_materializations_destination_pocket
        FOREIGN KEY (destination_pocket_id) REFERENCES pockets(id) ON DELETE SET NULL,
    CONSTRAINT fk_transaction_materializations_partner
        FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE SET NULL,
    CONSTRAINT uq_transaction_materializations_template_date
        UNIQUE (transaction_template_id, transaction_date)
);

CREATE INDEX idx_transaction_materializations_template_date
    ON transaction_materializations (transaction_template_id, transaction_date);
