CREATE TABLE transaction_projection_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_type VARCHAR(64) NOT NULL,
    aggregate_id BIGINT NULL,
    created_at BIGINT NOT NULL,
    processed_at BIGINT NULL
);

CREATE INDEX idx_transaction_projection_events_pending
    ON transaction_projection_events (processed_at, id);

CREATE TABLE account_transaction_feed (
    account_id BIGINT NOT NULL,
    transaction_id BIGINT NOT NULL,
    transaction_template_id BIGINT NOT NULL,
    history_position BIGINT NOT NULL,
    transaction_date VARCHAR(32) NOT NULL,
    type VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    transaction_amount BIGINT NOT NULL,
    signed_amount BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    partner_id BIGINT NULL,
    partner_name VARCHAR(255) NULL,
    source_pocket_id BIGINT NULL,
    source_pocket_name VARCHAR(255) NULL,
    source_pocket_color INTEGER NULL,
    destination_pocket_id BIGINT NULL,
    destination_pocket_name VARCHAR(255) NULL,
    destination_pocket_color INTEGER NULL,
    is_archived BOOLEAN NOT NULL,
    PRIMARY KEY (account_id, transaction_id),
    CONSTRAINT uq_account_transaction_feed_position UNIQUE (account_id, history_position),
    CONSTRAINT fk_account_transaction_feed_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_account_transaction_feed_transaction FOREIGN KEY (transaction_id) REFERENCES transaction_materializations(id) ON DELETE CASCADE,
    CONSTRAINT fk_account_transaction_feed_template FOREIGN KEY (transaction_template_id) REFERENCES transaction_templates(id) ON DELETE CASCADE,
    CONSTRAINT fk_account_transaction_feed_partner FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE SET NULL,
    CONSTRAINT fk_account_transaction_feed_source_pocket FOREIGN KEY (source_pocket_id) REFERENCES pockets(id) ON DELETE SET NULL,
    CONSTRAINT fk_account_transaction_feed_destination_pocket FOREIGN KEY (destination_pocket_id) REFERENCES pockets(id) ON DELETE SET NULL
);

CREATE INDEX idx_account_transaction_feed_account_position
    ON account_transaction_feed (account_id, history_position DESC);

CREATE INDEX idx_account_transaction_feed_account_date
    ON account_transaction_feed (account_id, transaction_date DESC, history_position DESC);

CREATE TABLE pocket_transaction_feed (
    pocket_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    transaction_id BIGINT NOT NULL,
    transaction_template_id BIGINT NOT NULL,
    history_position BIGINT NOT NULL,
    transaction_date VARCHAR(32) NOT NULL,
    type VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    transaction_amount BIGINT NOT NULL,
    signed_amount BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    partner_id BIGINT NULL,
    partner_name VARCHAR(255) NULL,
    transfer_pocket_id BIGINT NULL,
    transfer_pocket_name VARCHAR(255) NULL,
    transfer_pocket_color INTEGER NULL,
    is_archived BOOLEAN NOT NULL,
    PRIMARY KEY (pocket_id, transaction_id),
    CONSTRAINT uq_pocket_transaction_feed_position UNIQUE (pocket_id, history_position),
    CONSTRAINT fk_pocket_transaction_feed_pocket FOREIGN KEY (pocket_id) REFERENCES pockets(id) ON DELETE CASCADE,
    CONSTRAINT fk_pocket_transaction_feed_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_pocket_transaction_feed_transaction FOREIGN KEY (transaction_id) REFERENCES transaction_materializations(id) ON DELETE CASCADE,
    CONSTRAINT fk_pocket_transaction_feed_template FOREIGN KEY (transaction_template_id) REFERENCES transaction_templates(id) ON DELETE CASCADE,
    CONSTRAINT fk_pocket_transaction_feed_partner FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE SET NULL,
    CONSTRAINT fk_pocket_transaction_feed_transfer_pocket FOREIGN KEY (transfer_pocket_id) REFERENCES pockets(id) ON DELETE SET NULL
);

CREATE INDEX idx_pocket_transaction_feed_pocket_position
    ON pocket_transaction_feed (pocket_id, history_position DESC);

CREATE INDEX idx_pocket_transaction_feed_pocket_date
    ON pocket_transaction_feed (pocket_id, transaction_date DESC, history_position DESC);

CREATE TABLE contract_transaction_feed (
    contract_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    transaction_id BIGINT NOT NULL,
    transaction_template_id BIGINT NOT NULL,
    history_position BIGINT NOT NULL,
    transaction_date VARCHAR(32) NOT NULL,
    type VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    transaction_amount BIGINT NOT NULL,
    signed_amount BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    partner_id BIGINT NULL,
    partner_name VARCHAR(255) NULL,
    transfer_pocket_id BIGINT NULL,
    transfer_pocket_name VARCHAR(255) NULL,
    transfer_pocket_color INTEGER NULL,
    is_archived BOOLEAN NOT NULL,
    PRIMARY KEY (contract_id, transaction_id),
    CONSTRAINT uq_contract_transaction_feed_position UNIQUE (contract_id, history_position),
    CONSTRAINT fk_contract_transaction_feed_contract FOREIGN KEY (contract_id) REFERENCES pockets(id) ON DELETE CASCADE,
    CONSTRAINT fk_contract_transaction_feed_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_contract_transaction_feed_transaction FOREIGN KEY (transaction_id) REFERENCES transaction_materializations(id) ON DELETE CASCADE,
    CONSTRAINT fk_contract_transaction_feed_template FOREIGN KEY (transaction_template_id) REFERENCES transaction_templates(id) ON DELETE CASCADE,
    CONSTRAINT fk_contract_transaction_feed_partner FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE SET NULL,
    CONSTRAINT fk_contract_transaction_feed_transfer_pocket FOREIGN KEY (transfer_pocket_id) REFERENCES pockets(id) ON DELETE SET NULL
);

CREATE INDEX idx_contract_transaction_feed_contract_position
    ON contract_transaction_feed (contract_id, history_position DESC);

CREATE INDEX idx_contract_transaction_feed_contract_date
    ON contract_transaction_feed (contract_id, transaction_date DESC, history_position DESC);
