CREATE TABLE financial_profiles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    kind VARCHAR(32) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at BIGINT NOT NULL,
    CONSTRAINT ck_financial_profiles_name_not_blank CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_financial_profiles_kind CHECK (kind IN ('PERSON', 'GROUP'))
);

CREATE UNIQUE INDEX uq_financial_profiles_normalized_name
    ON financial_profiles (LOWER(BTRIM(name)));

CREATE UNIQUE INDEX uq_financial_profiles_single_default
    ON financial_profiles (is_default)
    WHERE is_default = TRUE;

INSERT INTO financial_profiles (name, description, kind, is_default, is_archived, created_at)
VALUES (
    'Unassigned',
    'Imported records that have not been classified yet',
    'GROUP',
    TRUE,
    FALSE,
    CAST(EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000 AS BIGINT)
);

ALTER TABLE contracts ADD COLUMN financial_profile_id BIGINT NULL;
ALTER TABLE transaction_templates ADD COLUMN financial_profile_id BIGINT NULL;
ALTER TABLE transaction_materializations ADD COLUMN financial_profile_id BIGINT NULL;

UPDATE contracts
SET financial_profile_id = (SELECT id FROM financial_profiles WHERE is_default = TRUE);

UPDATE transaction_templates
SET financial_profile_id = (SELECT id FROM financial_profiles WHERE is_default = TRUE);

UPDATE transaction_materializations materialization
SET financial_profile_id = template.financial_profile_id
FROM transaction_templates template
WHERE template.id = materialization.transaction_template_id;

ALTER TABLE contracts ALTER COLUMN financial_profile_id SET NOT NULL;
ALTER TABLE transaction_templates ALTER COLUMN financial_profile_id SET NOT NULL;
ALTER TABLE transaction_materializations ALTER COLUMN financial_profile_id SET NOT NULL;

ALTER TABLE contracts
    ADD CONSTRAINT fk_contracts_financial_profile
        FOREIGN KEY (financial_profile_id) REFERENCES financial_profiles(id) ON DELETE RESTRICT;

ALTER TABLE transaction_templates
    ADD CONSTRAINT fk_transaction_templates_financial_profile
        FOREIGN KEY (financial_profile_id) REFERENCES financial_profiles(id) ON DELETE RESTRICT;

ALTER TABLE transaction_materializations
    ADD CONSTRAINT fk_transaction_materializations_financial_profile
        FOREIGN KEY (financial_profile_id) REFERENCES financial_profiles(id) ON DELETE RESTRICT;

CREATE INDEX idx_contracts_financial_profile
    ON contracts (financial_profile_id);

CREATE INDEX idx_transaction_templates_financial_profile
    ON transaction_templates (financial_profile_id);

CREATE INDEX idx_transaction_materializations_financial_profile
    ON transaction_materializations (financial_profile_id);

ALTER TABLE account_transaction_feed
    ADD COLUMN financial_profile_id BIGINT NULL,
    ADD COLUMN financial_profile_name VARCHAR(255) NULL,
    ADD COLUMN financial_profile_kind VARCHAR(32) NULL;

ALTER TABLE pocket_transaction_feed
    ADD COLUMN financial_profile_id BIGINT NULL,
    ADD COLUMN financial_profile_name VARCHAR(255) NULL,
    ADD COLUMN financial_profile_kind VARCHAR(32) NULL;

ALTER TABLE contract_transaction_feed
    ADD COLUMN financial_profile_id BIGINT NULL,
    ADD COLUMN financial_profile_name VARCHAR(255) NULL,
    ADD COLUMN financial_profile_kind VARCHAR(32) NULL;

UPDATE account_transaction_feed feed
SET financial_profile_id = profile.id,
    financial_profile_name = profile.name,
    financial_profile_kind = profile.kind
FROM transaction_materializations materialization
JOIN financial_profiles profile ON profile.id = materialization.financial_profile_id
WHERE materialization.id = feed.transaction_id;

UPDATE pocket_transaction_feed feed
SET financial_profile_id = profile.id,
    financial_profile_name = profile.name,
    financial_profile_kind = profile.kind
FROM transaction_materializations materialization
JOIN financial_profiles profile ON profile.id = materialization.financial_profile_id
WHERE materialization.id = feed.transaction_id;

UPDATE contract_transaction_feed feed
SET financial_profile_id = profile.id,
    financial_profile_name = profile.name,
    financial_profile_kind = profile.kind
FROM transaction_materializations materialization
JOIN financial_profiles profile ON profile.id = materialization.financial_profile_id
WHERE materialization.id = feed.transaction_id;

ALTER TABLE account_transaction_feed
    ALTER COLUMN financial_profile_id SET NOT NULL,
    ALTER COLUMN financial_profile_name SET NOT NULL,
    ALTER COLUMN financial_profile_kind SET NOT NULL;

ALTER TABLE pocket_transaction_feed
    ALTER COLUMN financial_profile_id SET NOT NULL,
    ALTER COLUMN financial_profile_name SET NOT NULL,
    ALTER COLUMN financial_profile_kind SET NOT NULL;

ALTER TABLE contract_transaction_feed
    ALTER COLUMN financial_profile_id SET NOT NULL,
    ALTER COLUMN financial_profile_name SET NOT NULL,
    ALTER COLUMN financial_profile_kind SET NOT NULL;
