CREATE TABLE saving_goals (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    financial_profile_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    color INTEGER NOT NULL,
    target_amount BIGINT NOT NULL,
    currency_code VARCHAR(16) NOT NULL,
    target_date VARCHAR(32) NULL,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at BIGINT NOT NULL,
    CONSTRAINT fk_saving_goals_financial_profile
        FOREIGN KEY (financial_profile_id) REFERENCES financial_profiles(id) ON DELETE RESTRICT,
    CONSTRAINT ck_saving_goals_name_not_blank CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_saving_goals_target_amount_positive CHECK (target_amount > 0)
);

CREATE INDEX idx_saving_goals_financial_profile
    ON saving_goals(financial_profile_id);

ALTER TABLE pockets
    ADD COLUMN saving_goal_id BIGINT NULL,
    ADD CONSTRAINT fk_pockets_saving_goal
        FOREIGN KEY (saving_goal_id) REFERENCES saving_goals(id) ON DELETE RESTRICT;

ALTER TABLE pockets
    DROP CONSTRAINT ck_pockets_presentation_ownership;

ALTER TABLE pockets
    ADD CONSTRAINT ck_pockets_presentation_ownership CHECK (
        (
            contract_id IS NULL
            AND name IS NOT NULL
            AND color IS NOT NULL
        )
        OR
        (
            contract_id IS NOT NULL
            AND saving_goal_id IS NULL
            AND name IS NULL
            AND description IS NULL
            AND color IS NULL
            AND is_default = FALSE
        )
    ),
    ADD CONSTRAINT ck_pockets_single_managed_owner CHECK (
        NOT (contract_id IS NOT NULL AND saving_goal_id IS NOT NULL)
    ),
    ADD CONSTRAINT ck_pockets_saving_goal_not_default CHECK (
        saving_goal_id IS NULL OR is_default = FALSE
    );

CREATE UNIQUE INDEX uq_pockets_saving_goal_account
    ON pockets(saving_goal_id, account_id)
    WHERE saving_goal_id IS NOT NULL;

CREATE INDEX idx_pockets_saving_goal
    ON pockets(saving_goal_id);
